apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app
  labels:
    apps: projectapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projectapp

  template:
    metadata:
      labels:
        app: projectapp

    spec:
      containers:
      - name: projectapp
        image: dockernaveen04/projectapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

