apiVersion: v1
kind: Service

metadata:
  name: project-serviceapp
  labels:
    app: projectapp
spec:
  selector:
    app: projectapp

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer

